<?php

declare(strict_types=1);

// SPDX-FileCopyrightText: 2026 Fatih AKTAS <akfatih2@gmail.com>
// SPDX-License-Identifier: AGPL-3.0-or-later

namespace OCA\Kanso\SetupCheck;

use OCP\IConfig;
use OCP\IL10N;
use OCP\SetupCheck\ISetupCheck;
use OCP\SetupCheck\SetupResult;

/**
 * Admin-Overview setup check (#3747) for the two instance misconfigurations
 * that silently break Kanso features on real installs:
 *
 * - AJAX background jobs: due reminders ship on background jobs
 *   ({@see \OCA\Kanso\Cron\SendDueReminders}), and "ajax" mode only fires
 *   while someone has a page open - reminders lag or never run.
 * - Missing overwrite.cli.url: deep links generated outside an HTTP request
 *   (reminder emails, notifications from cron) fall back to localhost.
 *
 * Read-only by design: this reports, it never writes config.
 */
class InstanceConfigCheck implements ISetupCheck {
	public function __construct(
		private IConfig $config,
		private IL10N $l10n,
	) {
	}

	#[\Override]
	public function getCategory(): string {
		// Custom categories are merged into "system" in the Admin Overview.
		return 'kanso';
	}

	#[\Override]
	public function getName(): string {
		return $this->l10n->t('Kanso background jobs & email links');
	}

	#[\Override]
	public function run(): SetupResult {
		$issues = [];
		$linkToDoc = null;

		$cronMode = $this->config->getAppValue('core', 'backgroundjobs_mode', 'ajax');
		if ($cronMode === 'ajax') {
			$issues[] = $this->l10n->t(
				'Background jobs use AJAX mode, which only runs while a page is open - Kanso due reminders will lag or never be sent. Switch to system cron in Administration settings > Basic settings.'
			);
			$linkToDoc = 'https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html';
		}

		$cliUrl = trim($this->config->getSystemValueString('overwrite.cli.url', ''));
		if ($cliUrl === '') {
			$issues[] = $this->l10n->t(
				'"overwrite.cli.url" is not set in config.php - links in Kanso reminder emails and notifications generated by background jobs will point to the wrong address. Set it to the URL your users use to reach this instance.'
			);
		}

		if ($issues !== []) {
			return SetupResult::warning(implode("\n", $issues), $linkToDoc);
		}

		return SetupResult::success(
			$this->l10n->t('Background jobs use a server-side mode and "overwrite.cli.url" is set.')
		);
	}
}
