<?php

declare(strict_types=1);

// SPDX-FileCopyrightText: 2026 Fatih AKTAS <akfatih2@gmail.com>
// SPDX-License-Identifier: AGPL-3.0-or-later

namespace OCA\Kanso\Service\Backup;

/**
 * Where a scheduled backup run puts its files (#161). The two implementations -
 * {@see AppDataBackupTarget} and {@see FilesBackupTarget} - are the ONLY thing
 * that differs between the two destinations an administrator can pick; the zip
 * building, the naming and the retention sweep in
 * {@see \OCA\Kanso\Service\BackupService} are shared and run identically against
 * either. That is deliberate: a forked backup body is how one destination
 * quietly stops honouring retention.
 *
 * The contract is filename-addressed on purpose. Names are generated by Kanso
 * (`kanso-board-<id>-<UTC stamp>.zip`) and validated against
 * {@see \OCA\Kanso\Service\BackupService::isBackupName()} before they ever reach
 * an implementation, so nothing here has to defend against a traversal segment -
 * but equally, nothing here may accept a path.
 */
interface BackupTarget {
	/**
	 * A short human-readable description of where this target writes, for error
	 * messages and the last-run record. Never a secret, never a local FS path.
	 */
	public function describe(): string;

	/**
	 * Writes (or overwrites in place) one backup file from an open read stream.
	 * Overwrite is the same-second re-run case: the name is unique per second,
	 * so a collision means "this exact backup is being taken again".
	 *
	 * @param resource $stream
	 * @throws \Throwable when the bytes could not be stored
	 */
	public function write(string $name, $stream): void;

	/**
	 * Every file currently in the target, unfiltered. The caller filters by the
	 * board-scoped prefix - both for retention and for the admin listing.
	 *
	 * @return list<array{name: string, size: int, mtime: int}>
	 */
	public function listFiles(): array;

	/**
	 * Removes one file. A file that is already gone is success, not a failure -
	 * retention must not blow up on a concurrent delete. Anything else throws.
	 *
	 * @throws \Throwable when an existing file could not be removed
	 */
	public function delete(string $name): void;

	/**
	 * Opens one backup for reading. The caller owns the returned stream and must
	 * close it.
	 *
	 * @return resource
	 * @throws \OCP\Files\NotFoundException when no such file exists
	 */
	public function read(string $name);
}
